channels:
  - conda-forge

dependencies:
  - python=3.7.5
  - nodejs=16.14.2
  - pip=20.1
  - pip:
      - robotframework-browser==12.4.0
      - rpaframework==14.1.1 # https://rpaframework.org/releasenotes.html

rccPostInstall:
  - rfbrowser init
