channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - nodejs=14.17.4

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - robotframework-browser==10.0.2
      - rpaframework==11.5.2 # https://rpaframework.org/releasenotes.html

rccPostInstall:
  - rfbrowser init
